package com.jarod85.litesocial.youtube

import android.content.Context
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.Stream
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamType
import org.schabi.newpipe.extractor.stream.VideoStream
import java.io.File
import java.util.Locale

/**
 * Turns a video's streams into something expo-video (ExoPlayer) can play.
 *
 * YouTube serves separate video and audio files for anything above 360p. A
 * small DASH manifest listing them lets ExoPlayer play both together and
 * switch quality as bandwidth changes, the way NewPipe does it. The manifest
 * is a local file; the media itself streams from YouTube with range requests.
 * There are no ads: only the video's own streams are ever requested.
 *
 * The video's captions go into the same manifest as text tracks, so the
 * player lists them and fetches one only when it's turned on.
 */
object Playback {
  /** Phones gain nothing from more; it also keeps everything on H.264, which every device decodes in hardware. */
  private const val MAX_HEIGHT = 1080

  /**
   * Playable sources, best first. The app falls back to the next one if a
   * source fails to load: DASH (up to 1080p), then YouTube's HLS manifest,
   * then the single 360p file that has video and audio together.
   */
  fun sources(context: Context, info: StreamInfo): List<Map<String, Any?>> {
    val sources = mutableListOf<Map<String, Any?>>()
    val live = isLive(info)
    if (!live) {
      val video = adaptiveVideo(info)
      val audio = adaptiveAudio(info)
      if (video.isNotEmpty() && audio.isNotEmpty()) {
        val uri = writeManifest(context, info.id, manifest(durationMs(info, video + audio), video, audio, captions(info)))
        sources += mapOf("uri" to uri, "contentType" to "dash")
      }
    }
    if (info.hlsUrl.isNotEmpty()) sources += mapOf("uri" to info.hlsUrl, "contentType" to "hls")
    if (live && info.dashMpdUrl.isNotEmpty()) sources += mapOf("uri" to info.dashMpdUrl, "contentType" to "dash")
    info.videoStreams
      .filter { it.isUrl && it.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP }
      .maxByOrNull { height(it) }
      ?.let { sources += mapOf("uri" to it.content, "contentType" to "progressive") }
    return sources
  }

  /**
   * One DASH manifest per resolution, highest first, for picking the quality
   * by hand (the "auto" source above switches by itself). Empty for live
   * streams and videos without separate video and audio streams.
   */
  fun qualities(context: Context, info: StreamInfo): List<Map<String, Any?>> {
    if (isLive(info)) return emptyList()
    val video = adaptiveVideo(info)
    val audio = adaptiveAudio(info)
    if (video.isEmpty() || audio.isEmpty()) return emptyList()
    val duration = durationMs(info, video + audio)
    val captions = captions(info)
    return video.groupBy { height(it) }.entries.sortedByDescending { it.key }.map { (height, streams) ->
      val fps = streams.maxOf { it.fps }
      mapOf(
        "height" to height,
        "label" to if (fps > 30) "${height}p$fps" else "${height}p",
        "uri" to writeManifest(context, "${info.id}-$height", manifest(duration, streams, audio, captions)),
      )
    }
  }

  /** A caption track as the app lists it; [id] is also its id in the manifest. */
  data class Caption(val id: String, val language: String, val label: String, val autoGenerated: Boolean, val mimeType: String, val url: String) {
    fun toMap(): Map<String, Any?> = mapOf("id" to id, "language" to language, "label" to label, "autoGenerated" to autoGenerated)
  }

  /** Mime types of the caption formats ExoPlayer reads, preferred first. */
  private val CAPTION_FORMATS = linkedMapOf(MediaFormat.VTT to "text/vtt", MediaFormat.TTML to "application/ttml+xml")

  /**
   * The video's caption tracks: uploaded ones first, then YouTube's
   * automatic ones, each by name. Auto-translated captions aren't offered:
   * YouTube refuses them to clients like this one (HTTP 429).
   */
  fun captions(info: StreamInfo): List<Caption> =
    info.subtitles
      .filter { it.isUrl && it.format in CAPTION_FORMATS && it.languageTag.isNotBlank() }
      .groupBy { it.languageTag to it.isAutoGenerated }
      .values
      .map { tracks -> tracks.minBy { CAPTION_FORMATS.keys.indexOf(it.format) } }
      .map { it to captionLabel(it.languageTag, it.isAutoGenerated) }
      .sortedWith(compareBy({ it.first.isAutoGenerated }, { it.second.lowercase(Locale.getDefault()) }))
      .mapIndexed { index, (track, label) ->
        Caption("cc$index", track.languageTag, label, track.isAutoGenerated, CAPTION_FORMATS.getValue(track.format!!), track.content)
      }

  /** "Chinese (Simplified)", "English (auto-generated)", in the phone's language. */
  fun captionLabel(languageTag: String, autoGenerated: Boolean): String {
    val display = Locale.getDefault()
    val name = Locale.forLanguageTag(scriptTag(languageTag)).getDisplayName(display)
      .ifBlank { languageTag }
      .replaceFirstChar { it.titlecase(display) }
      // Android says "Chinese (Simplified Han)"; YouTube and everyone else say "Chinese (Simplified)".
      .replace(" Han)", ")")
    return if (autoGenerated) "$name (auto-generated)" else name
  }

  /** Chinese by region becomes Chinese by script ("zh-CN" is shown as Simplified Chinese). */
  fun scriptTag(languageTag: String): String {
    val parts = languageTag.split('-', '_')
    if (parts.first().lowercase() != "zh" || parts.size < 2) return languageTag
    return when (parts[1].uppercase()) {
      "HANS", "CN", "SG", "MY" -> "zh-Hans"
      "HANT", "TW", "HK", "MO" -> "zh-Hant"
      else -> languageTag
    }
  }

  private fun isLive(info: StreamInfo): Boolean =
    info.streamType == StreamType.LIVE_STREAM || info.streamType == StreamType.AUDIO_LIVE_STREAM

  /** Saves a manifest in the cache and returns its file:// URI. */
  private fun writeManifest(context: Context, name: String, manifest: String): String {
    val file = File(File(context.cacheDir, "youtube").apply { mkdirs() }, "$name.mpd")
    file.writeText(manifest)
    return "file://${file.absolutePath}"
  }

  /** H.264 MP4 video-only streams up to MAX_HEIGHT that have the byte ranges a DASH manifest needs. */
  fun adaptiveVideo(info: StreamInfo): List<VideoStream> =
    info.videoOnlyStreams
      .filter { usable(it) && it.format == MediaFormat.MPEG_4 && it.codec.orEmpty().startsWith("avc1") && height(it) in 1..MAX_HEIGHT }
      .distinctBy { it.itag }
      .sortedBy { it.bitrate }

  /** AAC audio in the video's original language (dubbed tracks are skipped). */
  fun adaptiveAudio(info: StreamInfo): List<AudioStream> {
    val aac = info.audioStreams.filter { usable(it) && it.format == MediaFormat.M4A }
    return originalTrack(aac).distinctBy { it.itag }.sortedBy { it.averageBitrate }
  }

  /** Of several audio tracks (original plus dubs), the original one; otherwise everything. */
  fun <T : AudioStream> originalTrack(streams: List<T>): List<T> {
    val byTrack = streams.groupBy { it.audioTrackId }
    if (byTrack.size <= 1) return streams
    return streams.filter { it.audioTrackType == AudioTrackType.ORIGINAL }.ifEmpty {
      byTrack.values.first()
    }
  }

  private fun usable(stream: Stream): Boolean {
    val (initEnd, indexStart, indexEnd) = when (stream) {
      is VideoStream -> Triple(stream.initEnd, stream.indexStart, stream.indexEnd)
      is AudioStream -> Triple(stream.initEnd, stream.indexStart, stream.indexEnd)
      else -> return false
    }
    return stream.isUrl && stream.deliveryMethod == DeliveryMethod.PROGRESSIVE_HTTP &&
      stream.itagItem != null && initEnd > 0 && indexStart > initEnd && indexEnd > indexStart
  }

  fun height(stream: VideoStream): Int =
    stream.height.takeIf { it > 0 } ?: Regex("(\\d+)p").find(stream.resolution.orEmpty())?.groupValues?.get(1)?.toIntOrNull() ?: 0

  private fun durationMs(info: StreamInfo, streams: List<Stream>): Long {
    val fromItags = streams.mapNotNull { it.itagItem?.approxDurationMs }.filter { it > 0 }.maxOrNull()
    return fromItags ?: (info.duration * 1000)
  }

  fun manifest(durationMs: Long, video: List<VideoStream>, audio: List<AudioStream>, captions: List<Caption> = emptyList()): String {
    val duration = String.format(Locale.US, "PT%.3fS", durationMs / 1000.0)
    val sb = StringBuilder()
    sb.append("""<?xml version="1.0" encoding="UTF-8"?>""").append('\n')
    sb.append("""<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" type="static" minBufferTime="PT1.500S" mediaPresentationDuration="$duration">""")
    sb.append("""<Period id="0" duration="$duration">""")

    sb.append("""<AdaptationSet id="0" contentType="video" mimeType="video/mp4" subsegmentAlignment="true" subsegmentStartsWithSAP="1">""")
    for (v in video) {
      val item = v.itagItem!!
      val width = item.width.takeIf { it > 0 } ?: (height(v) * 16 / 9)
      val fps = v.fps.takeIf { it > 0 }?.let { """ frameRate="$it"""" } ?: ""
      sb.append("""<Representation id="${v.itag}" codecs="${xml(v.codec)}" bandwidth="${maxOf(v.bitrate, 1)}" width="$width" height="${height(v)}"$fps>""")
      segment(sb, v.content, v.initStart, v.initEnd, v.indexStart, v.indexEnd)
      sb.append("</Representation>")
    }
    sb.append("</AdaptationSet>")

    sb.append("""<AdaptationSet id="1" contentType="audio" mimeType="audio/mp4" subsegmentAlignment="true" subsegmentStartsWithSAP="1">""")
    for (a in audio) {
      val item = a.itagItem!!
      val rate = item.sampleRate.takeIf { it > 0 }?.let { """ audioSamplingRate="$it"""" } ?: ""
      val bandwidth = a.bitrate.takeIf { it > 0 } ?: (a.averageBitrate * 1000)
      sb.append("""<Representation id="${a.itag}" codecs="${xml(a.codec)}" bandwidth="${maxOf(bandwidth, 1)}"$rate>""")
      sb.append("""<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="${item.audioChannels.takeIf { it > 0 } ?: 2}"/>""")
      segment(sb, a.content, a.initStart, a.initEnd, a.indexStart, a.indexEnd)
      sb.append("</Representation>")
    }
    sb.append("</AdaptationSet>")

    // Whole caption files, fetched once when turned on. Adaptation set ids must be numbers.
    captions.forEachIndexed { index, c ->
      sb.append("""<AdaptationSet id="${index + 2}" contentType="text" mimeType="${c.mimeType}" lang="${xml(c.language)}">""")
      sb.append("""<Role schemeIdUri="urn:mpeg:dash:role:2011" value="${if (c.autoGenerated) "caption" else "subtitle"}"/>""")
      sb.append("<Label>").append(xml(c.label)).append("</Label>")
      sb.append("""<Representation id="${c.id}" bandwidth="256">""")
      sb.append("<BaseURL>").append(xml(c.url)).append("</BaseURL>")
      sb.append("</Representation></AdaptationSet>")
    }

    sb.append("</Period></MPD>")
    return sb.toString()
  }

  private fun segment(sb: StringBuilder, url: String, initStart: Int, initEnd: Int, indexStart: Int, indexEnd: Int) {
    sb.append("<BaseURL>").append(xml(url)).append("</BaseURL>")
    sb.append("""<SegmentBase indexRange="$indexStart-$indexEnd"><Initialization range="$initStart-$initEnd"/></SegmentBase>""")
  }

  private fun xml(text: String?): String = (text ?: "")
    .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")
}
