/**
 * Bundles src/injected/engine.ts (plus the src/core modules it imports) into a
 * single string the app injects into the WebView.
 *
 * Why a build step: the injected script has to be a string, and Hermes doesn't
 * keep function source, so `fn.toString()` can't produce it at runtime.
 * Bundling also lets the page and the app share one tested route matcher.
 *
 * Run `npm run build:engine` after changing src/injected or src/core.
 * tests/engineSource.test.ts fails if the generated file is out of date.
 */
const { buildSync } = require('esbuild');
const { readFileSync, writeFileSync } = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const OUT_FILE = path.join(ROOT, 'src/injected/generated/engineSource.ts');

function buildEngineSource() {
  const result = buildSync({
    entryPoints: [path.join(ROOT, 'src/injected/engine.ts')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    // Old enough for every WebView we target (iOS 15+, current Android System WebView).
    target: ['es2019', 'safari15', 'chrome100'],
    minify: true,
    legalComments: 'none',
    write: false,
  });
  return result.outputFiles[0].text.trim();
}

function renderModule(source) {
  return [
    '// AUTO-GENERATED by scripts/build-engine.js from src/injected/engine.ts. Do not edit.',
    '// Run `npm run build:engine` after changing anything under src/injected/ or src/core/.',
    `export const ENGINE_SOURCE = ${JSON.stringify(source)};`,
    '',
  ].join('\n');
}

/** The committed generated module, with line endings normalized (Windows checkouts may use CRLF). */
function readGeneratedModule() {
  return readFileSync(OUT_FILE, 'utf8').replace(/\r\n/g, '\n');
}

module.exports = { buildEngineSource, renderModule, readGeneratedModule };

if (require.main === module) {
  const source = buildEngineSource();
  writeFileSync(OUT_FILE, renderModule(source));
  console.log(`Wrote ${path.relative(ROOT, OUT_FILE)} (${(source.length / 1024).toFixed(1)} KB)`);
}
