import type { CaptionTrack } from './types';

/**
 * What a language tag stands for when matching captions to the language you
 * picked before: Chinese by script (zh-CN and zh-Hans alike, zh-TW and
 * zh-Hant alike), anything else by its language ("en-GB" is "en").
 */
export function captionKey(tag: string): string {
  const [language = '', region = ''] = tag.toLowerCase().split(/[-_]/);
  if (language === 'zh') {
    if (['hans', 'cn', 'sg', 'my'].includes(region)) return 'zh-hans';
    if (['hant', 'tw', 'hk', 'mo'].includes(region)) return 'zh-hant';
  }
  return language;
}

/**
 * The captions to show for a video, given the language picked last time:
 * the same tag, else the same language, uploaded captions before automatic
 * ones. Null (off) if nothing was picked or the video has no such captions.
 */
export function pickCaption(captions: CaptionTrack[], language: string | null): CaptionTrack | null {
  if (!language) return null;
  const byKind = [...captions].sort((a, b) => Number(a.autoGenerated) - Number(b.autoGenerated));
  const tag = language.toLowerCase();
  const key = captionKey(language);
  return byKind.find((c) => c.language.toLowerCase() === tag) ?? byKind.find((c) => captionKey(c.language) === key) ?? null;
}
